version: '2'
services:
  proxy:
    image: nginx
    links:
    - registry
    ports:
    - 4111:80
    volumes:
    - .htpasswd:/etc/nginx/.htpasswd:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  registry:
    restart: always
    image: registry:2
    ports:
    - 5000:5000
    environment:
      REGISTRY_HTTP_HOST: http://localhost:5000 
      REGISTRY_LOG_LEVEL: debug
    #   SETTINGS_FLAVOR: local
    #   STORAGE_PATH: /var/lib/docker/registry

